# Generated by Django 4.2.2 on 2023-08-05 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='listWatchlisting', to=settings.AUTH_USER_MODEL),
        ),
    ]
