# Generated by Django 4.2.2 on 2024-01-07 22:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='finalPrice',
        ),
        migrations.AddField(
            model_name='listing',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.CharField(default='https://boodabike.com/wp-content/uploads/2023/03/no-image.jpg', max_length=800),
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
