# Generated by Django 4.2.2 on 2024-01-13 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_listing_finalprice_listing_requests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='sold',
            field=models.TextField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
