# Generated by Django 4.2.2 on 2024-02-11 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='requests',
        ),
    ]
