# Generated by Django 4.2.2 on 2024-02-14 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_comment_listing_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='NAMEcategory',
            new_name='name',
        ),
    ]
