# Generated by Django 4.2.2 on 2024-02-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_rename_namecategory_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='ISactive',
            new_name='is_active',
        ),
    ]
