# Generated by Django 4.2.2 on 2024-02-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_listing_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=models.ImageField(blank=True, default='listing_images/no-image.jpg', null=True, upload_to='listing_images'),
        ),
    ]
