# Generated by Django 4.2.2 on 2024-02-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_listing_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
    ]
