# Generated by Django 4.2.2 on 2024-02-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_remove_listing_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='img',
            new_name='image',
        ),
    ]
