# Generated by Django 4.2.2 on 2024-02-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_rename_img_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='listing_images'),
        ),
    ]
