# Generated by Django 5.0.2 on 2024-02-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Success', 'Success'), ('Danger', 'Danger')], default='Normal', max_length=20),
        ),
    ]
