# Generated by Django 5.0.2 on 2024-02-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_listing_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reference_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
